apiVersion: batch/v1
kind: Job
metadata:
  name: backend-prestart
  namespace: stage
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  backoffLimit: 2
  activeDeadlineSeconds: 240
  ttlSecondsAfterFinished: 180
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: prestart
          image: charansait372/backend:v1
          command: ["sh", "-c"]
          args:
            - |
              echo "Running prestart tasks..."
              python prestart.py
          resources:
            requests:
              cpu: 75m
              memory: 96Mi
            limits:
              cpu: 300m
              memory: 384Mi

