apiVersion: v1
kind: LimitRange
metadata:
  name: stage-limits
  namespace: stage
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 75m
        memory: 96Mi
      default:
        cpu: 400m
        memory: 384Mi
      min:
        cpu: 50m
        memory: 64Mi
      max:
        cpu: "1500m"
        memory: 1500Mi

