apiVersion: batch/v1
kind: Job
metadata:
  name: backend-prestart
  namespace: prod
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  backoffLimit: 3
  activeDeadlineSeconds: 300
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: prestart
          image: charansait372/backend:v1
          command: ["sh", "-c"]
          args:
            - |
              echo "Running prestart tasks..."
              python prestart.py
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi

